import { test,expect } from '@playwright/test';
test('orden global de capas, carga diferida, recarga y vistas guardadas',async({page})=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  // Block service workers so the delayed geometry route is deterministic in both engines.
  await page.context().route('**/sw.js',route=>route.abort());
  let releaseGeometry;
  const geometryGate=new Promise(resolve=>{releaseGeometry=resolve;});
  await page.route('**/*cuencas_nivel3_ine*.geojson',async route=>{await geometryGate;await route.continue();});
  await page.goto('/');await page.locator('#enterMap').click();
  await page.waitForFunction(()=>geoData.apn&&geoData.departamentos);
  await page.locator('#baseOpen').click();await page.locator('[data-base="none"]').click();
  await page.locator('[data-panel="layers"]').click();await page.locator('[data-catalog="8"]').click();
  await page.locator('.group-button[data-group="Marco espacial"]').click();
  await page.getByRole('switch',{name:'Cuencas Hidrográficas (Nivel 3)',exact:true}).click();
  await page.locator('#sheetClose').click();await page.locator('[data-panel="active"]').click();
  const rows=page.locator('.active-stack .mobile-layer');
  const keys=()=>rows.evaluateAll(nodes=>nodes.map(el=>el.dataset.module+':'+el.dataset.layer));
  const initial=await keys();expect(initial[0]).toBe('8:ine_cuencas_n3');
  const basin=page.locator('.active-stack [data-layer="ine_cuencas_n3"]');
  await expect(basin.locator('[data-action="up"]')).toBeDisabled();
  await basin.locator('[data-action="down"]').click();
  const reordered=await keys();expect(reordered[1]).toBe(initial[0]);expect(reordered[0]).toBe(initial[1]);
  releaseGeometry();
  await page.waitForFunction(()=>geoData.ine_cuencas_n3?.features?.length>0);
  const paneOrder=()=>page.evaluate(()=>{
    const entries=MobileUI.getState().active;
    return entries.map(({module,id})=>{
      const layer=moduleLayers[module+':'+id],pane=map.getPane(layer.options.pane),descendants=[];
      const inspect=l=>{if(l instanceof L.Path)descendants.push(l.getElement()?.closest('[data-layer-key]')?.dataset.layerKey);if(l.eachLayer)l.eachLayer(inspect);};inspect(layer);
      return {key:module+':'+id,z:Number(pane.style.zIndex),visible:map.hasLayer(layer),descendants};
    });
  });
  let actual=await paneOrder();
  expect(actual.map(x=>x.key)).toEqual(reordered);
  expect(actual.every((x,i)=>x.visible&&x.z===actual.length-i&&x.descendants.every(key=>key===x.key))).toBe(true);
  expect(actual.find(x=>x.key==='8:ine_cuencas_n3').descendants.length).toBeGreaterThan(0);
  await expect(rows.last().locator('[data-action="down"]')).toBeDisabled();
  await page.screenshot({path:`outputs/07-orden-capas-${test.info().project.name}.png`,animations:'disabled'});
  await page.locator('#sheetClose').click();await page.locator('[data-panel="more"]').click();await page.locator('#saveView').click();
  await page.locator('#sheetClose').click();await page.locator('[data-panel="active"]').click();
  await basin.locator('[data-action="up"]').click();expect(await keys()).toEqual(initial);
  await page.locator('#sheetClose').click();await page.locator('[data-panel="more"]').click();await page.locator('#savedViews').click();await page.locator('[data-view="0"]').click();
  await page.locator('[data-panel="active"]').click();expect(await keys()).toEqual(reordered);
  await page.reload();await page.waitForFunction(()=>MobileUI.getState().currentModule==='8');
  await page.locator('[data-panel="active"]').click();expect(await keys()).toEqual(reordered);
  await basin.locator('.layer-toggle').click();
  await page.locator('#sheetClose').click();await page.locator('[data-panel="layers"]').click();await page.locator('[data-catalog="8"]').click();
  await page.locator('.group-button[data-group="Marco espacial"]').click();await page.getByRole('switch',{name:'Cuencas Hidrográficas (Nivel 3)',exact:true}).click();
  await page.locator('#sheetClose').click();await page.locator('[data-panel="active"]').click();expect(await keys()).toEqual(reordered);
  await page.locator('#sheetClose').click();await page.locator('[data-panel="layers"]').click();await page.locator('[data-catalog="1"]').click();
  await page.locator('#sheetClose').click();await page.locator('[data-panel="active"]').click();expect(await keys()).toEqual(reordered);
  actual=await paneOrder();expect(actual.every((x,i)=>x.visible&&x.z===actual.length-i)).toBe(true);
  expect(errors).toEqual([]);
});

test('orden de teselas WMS y geometrías vectoriales en el mismo mapa',async({page})=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.route('https://geoserver.inra.gob.bo/**',route=>route.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="256" height="256"><rect width="256" height="256" fill="#bbdddd"/></svg>'}));
  await page.goto('/');await page.locator('#enterMap').click();
  await page.waitForFunction(()=>geoData.apn&&geoData.departamentos);
  await page.locator('[data-panel="layers"]').click();await page.locator('[data-catalog="3"]').click();
  await page.locator('.group-button[data-group="SINACAR / INRA"]').click();await page.getByRole('switch',{name:'Amenaza de inundación',exact:true}).click();
  await page.locator('#sheetClose').click();await page.locator('[data-panel="active"]').click();
  const row=page.locator('.active-stack [data-layer="wms_amenaza_inundacion"]');
  const inspect=()=>page.evaluate(()=>{
    const raster=moduleLayers['3:wms_amenaza_inundacion'],vector=moduleLayers['1:departamentos'];
    let path;vector.eachLayer(child=>{if(child instanceof L.Path)path=child;});
    const rasterPane=raster.getContainer().closest('[data-layer-key]'),vectorPane=path.getElement().closest('[data-layer-key]');
    raster.bringToFront();path.bringToFront();
    return {rasterKey:rasterPane.dataset.layerKey,vectorKey:vectorPane.dataset.layerKey,above:Number(rasterPane.style.zIndex)>Number(vectorPane.style.zIndex),parent:rasterPane.parentElement===vectorPane.parentElement};
  });
  expect(await inspect()).toEqual({rasterKey:'3:wms_amenaza_inundacion',vectorKey:'1:departamentos',above:true,parent:true});
  while(!await row.locator('[data-action="down"]').isDisabled())await row.locator('[data-action="down"]').click();
  expect((await inspect()).above).toBe(false);
  while(!await row.locator('[data-action="up"]').isDisabled())await row.locator('[data-action="up"]').click();
  expect((await inspect()).above).toBe(true);
  expect(errors).toEqual([]);
});

test('navegación móvil, grupos, capas persistentes y descargas INE',async({page})=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('/');
  await expect(page.locator('#enterMap')).toBeVisible();
  await page.screenshot({path:'outputs/01-bienvenida.png'});
  await page.locator('#enterMap').click();
  await page.waitForFunction(()=>window.MobileUI);
  await expect(page.locator('#mobileSheet')).toBeHidden();
  expect(await page.locator('#map').boundingBox()).toMatchObject({width:390,height:844});
  await page.screenshot({path:'outputs/02-mapa.png'});
  await page.locator('[data-panel="layers"]').click();
  await expect(page.locator('[data-catalog]')).toHaveCount(9);
  await page.screenshot({path:'outputs/03-modulos.png',animations:'disabled'});
  await page.locator('[data-catalog="8"]').click();
  await expect(page.locator('.group-button')).toHaveCount(2);
  await expect(page.locator('.mobile-layer')).toHaveCount(0);
  await page.locator('.group-button[data-group="Marco espacial"]').click();
  const basin=page.getByRole('switch',{name:'Cuencas Hidrográficas (Nivel 3)',exact:true});
  await expect(basin).toHaveAttribute('aria-checked','false');
  await basin.click();
  await expect(basin).toHaveAttribute('aria-checked','true');
  await page.waitForFunction(()=>typeof geoData!=='undefined'&&geoData.ine_cuencas_n3?.features?.length>0);
  await page.screenshot({path:'outputs/04-grupos-capas.png',animations:'disabled'});
  await page.locator('#sheetClose').click();
  await page.locator('[data-panel="active"]').click();
  await expect(page.locator('.mobile-layer[data-layer="ine_cuencas_n3"]')).toBeVisible();
  await expect(page.locator('.mobile-layer[data-layer="apn"]')).toBeVisible();
  await page.locator('#sheetClose').click();
  await page.locator('[data-panel="data"]').click();
  await expect(page.getByRole('button',{name:'Por cuenca',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Por cuenca',exact:true}).click();
  await expect(page.getByRole('link',{name:'Descargar Excel'})).toBeVisible();
  await page.screenshot({path:'outputs/05-datos-cuencas.png',animations:'disabled'});
  const excel=page.getByRole('link',{name:'Descargar Excel'});
  const url=await excel.getAttribute('href');expect((await page.request.get(url)).status()).toBe(200);
  await page.locator('.m8-basin-row:not(.no-data)').first().click();
  await expect(page.getByRole('link',{name:'Descargar ficha PDF',exact:true})).toBeVisible();
  const pdf=await page.getByRole('link',{name:'Descargar ficha PDF',exact:true}).getAttribute('href');
  expect((await page.request.get(pdf)).status()).toBe(200);
  await page.locator('#m8BasinAPFilter').click();
  await expect(page.locator('#m8BasinAPFilter')).toHaveAttribute('aria-pressed','true');
  await expect(page.locator('.m8-basin-row')).toHaveCount(45);
  await page.locator('#m8ClearBasin').click();
  await expect(page.locator('#m8ClearBasin')).toBeDisabled();
  await page.getByRole('button',{name:'Datos puntuales',exact:true}).click();
  await page.locator('#m8Rectangle').click();
  await expect(page.locator('#mobileSheet')).toBeHidden();
  await expect(page.locator('.mobile-draw-bar')).toBeVisible();
  await page.locator('#map').tap({position:{x:100,y:210}});
  await page.locator('#map').tap({position:{x:210,y:320}});
  await expect(page.locator('.mobile-draw-bar')).toBeHidden();
  await page.locator('[data-panel="data"]').click();
  await page.locator('#sheetClose').click();
  await page.locator('#baseOpen').click();await page.locator('[data-base="none"]').click();
  expect(await page.evaluate(()=>window.MobileUI.getState().base)).toBe('none');
  await page.locator('#searchOpen').click();await page.locator('#mobileSearch').fill('cuencas');
  await expect(page.locator('[data-result]').first()).toBeVisible();
  await page.locator('#sheetClose').click();
  await page.locator('[data-panel="more"]').click();await page.locator('#saveView').click();await page.locator('#savedViews').click();await expect(page.locator('[data-view]')).toHaveCount(1);
  await page.locator('#sheetClose').click();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
  expect(errors).toEqual([]);
});

test('tableta sin desbordamiento y cambio entre nueve módulos',async({page})=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.setViewportSize({width:820,height:1180});await page.goto('/');await page.locator('#enterMap').click();
  await page.locator('#baseOpen').click();await page.locator('[data-base="none"]').click();
  await page.screenshot({path:'outputs/06-tableta.png'});
  for(const id of ['2','3','4','5','6','7','8','9','1']){
    await page.locator('[data-panel="layers"]').click();await page.locator(`[data-catalog="${id}"]`).click();
    expect(await page.evaluate(()=>window.MobileUI.getState().currentModule)).toBe(id);
    await page.locator('#sheetClose').click();await page.locator('[data-panel="data"]').click();
    await expect(page.locator('#sheetTitle')).toHaveText('Datos del territorio');await page.locator('#sheetClose').click();
  }
  expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(820);expect(errors).toEqual([]);
});

test('PWA reabre sin conexión con datos INE',async({page,context,browserName})=>{
  test.skip(browserName==='webkit','Playwright no admite pruebas de service workers en WebKit; verificar en iPhone real. https://playwright.dev/docs/service-workers');
  await page.goto('/');await page.locator('#enterMap').click();
  await page.waitForFunction(()=>navigator.serviceWorker.controller!==null,null,{timeout:60000});
  await page.locator('#baseOpen').click();await page.locator('[data-base="none"]').click();
  await context.setOffline(true);await page.reload();await page.waitForFunction(()=>window.MobileUI);
  await expect(page.locator('#offlineBadge')).toBeVisible();await expect(page.locator('#enterMap')).toBeHidden();
  await page.locator('[data-panel="layers"]').click();await expect(page.locator('[data-catalog]')).toHaveCount(9);
  await page.locator('[data-catalog="8"]').click();await page.locator('#sheetClose').click();
  await page.locator('[data-panel="data"]').click();await page.getByRole('button',{name:'Por cuenca',exact:true}).click();
  await expect(page.locator('.m8-basin-row')).toHaveCount(67);
});
